#!/usr/bin/env python3

# Copyright (c) 2022 Trevor Taylor
# coding: utf-8
# 
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that all
# copyright notices and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
from sys import path
from os.path import dirname
if path[0]==dirname(__file__): path.pop(0)
from xju import cmc

import asyncio
from xju.assert_ import Assert
from typing import cast, Awaitable

try:
    cmc._is_subclass('fred', 7, cast(type, 'jock'))
except Exception as e:
    Assert("'jock' is not an instance of class type (it is of class str)").isIn(str(e))
    pass


async def async_main() -> None:
    async def task_that_succeeds() -> int:
        return 3

    task: Awaitable[int]

    async with cmc.Task(task_that_succeeds()) as task:
        Assert(task.done())==False
        pass
    Assert(task.done())==True
    Assert(task.cancelled())==True

    async with cmc.Task(task_that_succeeds()) as task:
        Assert(task.done())==False
        Assert(await task)==3
        Assert(task.done())==True
        pass
    Assert(task.cancelled())==False

    async def task_that_raises_exception():
        raise Exception('failed to do anything')

    async with cmc.Task(task_that_raises_exception()) as task:
        Assert(task.done())==False
        pass
    Assert(task.done())==True
    Assert(task.cancelled())==True

    try:
        async with cmc.Task(task_that_raises_exception()) as task:
            Assert(task.done())==False
            result=await task
            pass
    except Exception as e:
        Assert("failed to do anything").isIn(str(e))
    else:
        assert False, result

asyncio.run(async_main())
