pyoso/__init__.py,sha256=pGcyBcTF0baurv-yj-c3XgSkKX1dWkClFqvPT7snbKE,195
pyoso/client.py,sha256=86UcIqZFVOS72lsDP_ylvTOXTOx82lWhf_oT4nM2Yjo,1488
pyoso/exceptions.py,sha256=3S9gY6ndSmAENPPVYeY4tI6yyx91dngF0owZUykJUUM,278
pyoso-0.1.1.dist-info/METADATA,sha256=9HGgKc6WT5gqAOGW797GUUyaJF5yTD9a4bagmDGCpwk,1130
pyoso-0.1.1.dist-info/WHEEL,sha256=In9FTNxeP60KnTkGw7wk6mJPYd_dQSjEZmXdBdMCI-8,91
pyoso-0.1.1.dist-info/top_level.txt,sha256=xKfiZHJRt0V88DxPF1o_MOL27K5GTngL94ORwalzi6A,6
pyoso-0.1.1.dist-info/RECORD,,
